model:
  device_map: auto
  trust_remote_code: true

generate:
  max_new_tokens: 256
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.05

data:
  test_file: data/jsquad-train-v1.1.json
  n_examples: 100

outputs:
  dirname: outputs
  filename: generated_text.jsonl

prompt: |-
  タイトル: {title}
  
  文脈: {context}

  設問: {question}

  答え: 